name: Daily Azair Scraper

on:
  schedule:
    - cron: "0 6 * * *"  # kasdien 06:00 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper/azair_scraper.py

      - name: Commit CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/flights.csv
          git commit -m "Daily flight data update" || echo "No changes to commit"
          git push

      - name: Upload debug HTML
        uses: actions/upload-artifact@v4
        with:
          name: azair_page_debug
          path: azair_page_debug.html
