name: scrape

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # kasdien 8 valandą ryto

permissions:
  contents: write  # leidžia GitHub Actions rašyti į repozitoriją

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pandas

      - name: Run scraper
        run: |
          python scraper/azair_scraper.py

      - name: Commit CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/azair_data.csv
          git commit -m "Daily flight data update" || echo "No changes to commit"
          git push

      - name: Upload debug HTML
        uses: actions/upload-artifact@v4
        with:
          name: azair-page-debug
          path: azair_page_debug.html
