name: Daily Azair Scraper

on:
  schedule:
    - cron: "0 4 * * *"        # kasdien 04:00 UTC ≈ 07:00 LT
  workflow_dispatch:           # leidžia paleisti rankiniu būdu

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # reikia, kad galėtų commitinti CSV
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper/azair_scraper.py

      - name: Commit CSV
        uses: EndBug/add-and-commit@v9
        with:
          message: "Daily flight data update"
          add: "data/flights.csv"
